inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 2.7.2

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Enabled: False

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/base_controller.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20200427093834_create_agents_users_join_table.rb'
    - 'db/migrate/20201005094454_extract_sectors.rb'
    - 'db/migrate/20210301135256_create_territories.rb'

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: False
