inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 2.7.2

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/LineLength:
  Max: 200

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*' # Inheriting BaseService without calling super is OK.

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8 # default is 7

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/base_controller.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20210301135256_create_territories.rb'

Rails/Delegate:
  Exclude:
    - 'config/initializers/recurrence_monkey_patch.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/features/agents/admin_can_configure_the_organisation_spec.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/matomo.rake'

RSpec/AnyInstance:
  Exclude:
    - spec/controllers/admin/users_controller_spec.rb
    - spec/controllers/admin/referents_controller_spec.rb

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 10

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/agent/*_policy_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

