inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "db/schema.rb"

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousOperator:
  Exclude:
    - 'app/controllers/application_controller.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
