inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "db/schema.rb"

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
