inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/EmptyBlock:
  Enabled: False
