inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Lint/UnexpectedBlockArity:
  Enabled: false
Lint/UnmodifiedReduceAccumulator:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/CollectionCompact:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
Style/NilLambda:
  Enabled: false
Style/RedundantArgument:
  Enabled: false
Style/SwapValues:
  Enabled: false
