inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 2.7.2

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/EmptyBlock:
  Enabled: False

RSpec/ContextWording:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive
