name: CI
on: push
jobs:
  rubocop:
    name: Lint Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle exec rubocop --parallel
  brakeman:
    name: Static Analysis Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle exec brakeman

  test_seeds:
    name: "Test DB Seeds"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle exec rake db:create db:schema:load db:migrate db:seed RAILS_ENV=test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1, 2, 3, 4]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install JS dependencies
        run: yarn install
      - name: Run specs
        run: ./scripts/rspec_splitted.rb
        env:
          HOST: http://example.com
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
          NUMBER_OF_NODES: 5
          CI_NODE_INDEX: ${{ matrix.index }}
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: "deploie demo"
    runs-on: ubuntu-latest
    environment: lapin-beta-gouv
    needs: [tests, brakeman, test_seeds, rubocop]
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          echo "Creating TAR archive..."
          tar --transform='s,^,master/,' -czf /tmp/archive.tar.gz .
          echo "Downloading scaliogo CLI"
          version=$(curl -s https://cli-dl.scalingo.com/version | tr -d ' \t\n')
          curl -L https://github.com/Scalingo/cli/releases/download/${version}/scalingo_${version}_linux_amd64.tar.gz -o /tmp/scalingo_cli.tar.gz
          mkdir /tmp/scalingo_cli
          tar -C /tmp/scalingo_cli -xf /tmp/scalingo_cli.tar.gz
          export PATH=$PATH:/tmp/scalingo_cli/scalingo_${version}_linux_amd64
          echo "Authenticating..."
          scalingo login --api-token $API_TOKEN
          echo "Starting deployment"
          scalingo --region $REGION --app $APP_NAME deploy /tmp/archive.tar.gz
        env:
          REGION: osc-secnum-fr1
          APP_NAME: demo-rdv-solidarites-pr1264
          API_TOKEN: ${{secrets.SCALINGO_API_TOKEN}}

