name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install dependencies
        run: bundle install && yarn install
        #- name: Rubocp
        #run: bundle exec rubocop
      - name: Brakeman
        run: bundle exec brakeman
      - name: Test
        run: bundle exec rspec
        env:
          HOST: http://example.com
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test

