name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: "CultureHQ/actions-bundler@master"
      with:
        args: install
    - name: Test
      run: make test
