name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  brakeman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install dependencies
        run: bundle install && yarn install
      - name: Brakeman
        run: bundle exec brakeman

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        index: [0, 1, 2, 3, 4]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install dependencies
        run: bundle install && yarn install
      - name: Test
        run: ./scripts/rspec_splitted.rb
        env:
          HOST: http://example.com
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test
          NUMBER_OF_NODES: 5
          CI_NODE_INDEX: ${{ matrix.index }}
